AWSTemplateFormatVersion: '2010-09-09'
Description: Laboratorio AWS Alta Disponibilidad con 5 EC2

Resources:

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP y SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance1:
    Type: AWS::EC2::Instance
    Properties: &InstanceProps
      InstanceType: t3.micro
      ImageId: ami-0c02fb55956c7d316
      KeyName: miservicioweb
      SecurityGroups:
        - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl start nginx
          systemctl enable nginx
          echo "<h1>Servidor AWS - Juan Pablo Gonzalez Leal</h1>" > /usr/share/nginx/html/index.html

  WebInstance2:
    Type: AWS::EC2::Instance
    Properties: *InstanceProps

  WebInstance3:
    Type: AWS::EC2::Instance
    Properties: *InstanceProps

  WebInstance4:
    Type: AWS::EC2::Instance
    Properties: *InstanceProps

  WebInstance5:
    Type: AWS::EC2::Instance
    Properties: *InstanceProps

  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: !GetAZs ''
      Instances:
        - !Ref WebInstance1
        - !Ref WebInstance2
        - !Ref WebInstance3
        - !Ref WebInstance4
        - !Ref WebInstance5
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP

Outputs:
  LoadBalancerDNS:
    Description: DNS del balanceador
    Value: !GetAtt LoadBalancer.DNSName